# Question 1

In [22]:
import numpy as np
import pandas as pd

In [23]:
def compute_mean_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

def main():
    N = 5
    # Create a random feature vector of size 1xN
    feature_vector = np.random.rand(1, N)
    
    print("Feature Vector:", feature_vector)
    
    mean, variance = compute_mean_variance(feature_vector)
    print("Mean:", mean)
    print("Variance:", variance)

if __name__ == "__main__":
    main()

Feature Vector: [[0.62489218 0.58355342 0.72015719 0.49501537 0.83121954]]
Mean: 0.6509675396372423
Variance: 0.013364731118767048


In [24]:
#The mean (average) of a set of numbers is calculated by summing up all the numbers and then dividing by the 
#total count of numbers.

#The variance measures how much the numbers in a set differ from the mean. 
#It is calculated by taking the average of the squared differences between each number and the mean.

# Question 2

In [25]:
import pandas as pd
import numpy as np

In [26]:
def compute_covariance(vector1,vector2):
    covariance = np.cov(vector1,vector2)
    return covariance[0,1]

def main():
    M = 5
    # Create a random feature vector of size 1xM
    feature_vector1 = np.random.rand(1, M)
    feature_vector2 = np.random.rand(1, M)
    
    print("Feature Vector 1:", feature_vector1)
    print("Feature Vector 2:", feature_vector2)
    
    covariance = compute_covariance(feature_vector1,feature_vector2)
    print("Covariance:", covariance)

if __name__ == "__main__":
    main()

Feature Vector 1: [[0.48745069 0.25964255 0.1763026  0.81508995 0.15923594]]
Feature Vector 2: [[0.08511309 0.6386546  0.589987   0.8987815  0.03607493]]
Covariance: 0.04905278588011164


In [27]:
#Covariance between two vectors represents how much two variables change together. In other words, it measures the degree to 
#which the variables tend to deviate from their respective means in similar ways.

#If the covariance between two variables is positive, it indicates that when one variable has a higher than average value, 
#the other variable tends to have a higher than average value as well. Conversely, if the covariance is negative, 
#it suggests that when one variable has a higher than average value, the other tends to have a lower than average value.

# Question 3

In [28]:
import pandas as pd
import numpy as np

In [29]:
def compute_correlation(vector1,vector2):
    correlation = np.corrcoef(vector1,vector2)
    return correlation[-1,1]

def main():
    N = 5
    # Create a random feature vector of size 1xN
    feature_vector1 = np.random.rand(1, N)
    feature_vector2 = np.random.rand(1, N)
    
    print("Feature Vector 1:", feature_vector1)
    print("Feature Vector 2:", feature_vector2)
    
    correlation = compute_correlation(feature_vector1,feature_vector2)
    print("Correlation:", correlation)

if __name__ == "__main__":
    main()

Feature Vector 1: [[0.72431988 0.05511804 0.71720778 0.4647789  0.69838332]]
Feature Vector 2: [[0.85459641 0.50939353 0.7323639  0.51498466 0.1975878 ]]
Correlation: 1.0


In [18]:
# Correlation represents the strength and direction of the linear relationship between two variables. 
# Unlike covariance, correlation is a standardized measure, meaning it is not affected by the scale of the variables. 
# It provides a more interpretable measure of the relationship between variables.

# The correlation coefficient, often denoted by r, ranges from -1 to 1.

# r=1: Perfect positive correlation. It indicates that as one variable increases, 
#     the other variable also increases in a perfectly linear manner.
# r=−1: Perfect negative correlation. It indicates that as one variable increases, 
#     the other variable decreases in a perfectly linear manner.

# Question 4

In [19]:
def compute_covariance_matrix(matrix):
    # Compute covariance matrix
    covariance_matrix = np.cov(matrix)

    return covariance_matrix

def compute_correlation_matrix(matrix):
    # Compute correlation matrix
    correlation_matrix = np.corrcoef(matrix)

    return correlation_matrix

def main():
    # Example feature matrix with 3 features (M=3) and 5 samples (N=5)
    feature_matrix = np.array([[1, 2, 3, 4, 5],
                                [2, 3, 4, 5, 6],
                                [3, 4, 5, 6, 7]])

    print("Feature Matrix:")
    print(feature_matrix)

    covariance_matrix = compute_covariance_matrix(feature_matrix)
    print("\nCovariance Matrix:")
    print(covariance_matrix)

    correlation_matrix = compute_correlation_matrix(feature_matrix)
    print("\nCorrelation Matrix:")
    print(correlation_matrix)

if __name__ == "__main__":
    main()

Feature Matrix:
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]

Covariance Matrix:
[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Takeaways from these matrices:

# Covariance Matrix:

# =Diagonal elements represent the variance of each feature.
# =Off-diagonal elements represent the covariance between pairs of features.
# =Positive values indicate a positive relationship (increase in one feature corresponds to an increase in the other), 
# while negative values indicate a negative relationship (increase in one feature corresponds to a decrease in the other).
# =The magnitude of the covariance depends on the scale of the features, making it difficult to interpret the strength of the 
# relationship.

# Correlation Matrix:

# =Similar to the covariance matrix, but it is standardized, with values ranging from -1 to 1.
# =Diagonal elements are always 1, representing the perfect correlation between each feature and itself.
# =Off-diagonal elements represent the correlation coefficients between pairs of features.
# =Provides a clearer indication of the strength and direction of the linear relationship between features since 
# it's not affected by the scale of the features.

# These matrices are useful in understanding the relationships between different features in the dataset. 
# A high correlation (either positive or negative) between two features might suggest redundancy or multicollinearity 
# in the dataset, which could impact the performance of certain algorithms like linear regression. Conversely, a low 
# correlation might indicate that the features are independent of each other.